---

- name: Remove IAM Roles
  iam:
    iam_type: role
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ iam_master_role }}"
    - "{{ iam_worker_role }}"
